# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "dok.arealanalyse.pygeoapi"
  tags:
  - "internal"
spec:
  type: "service"
  lifecycle: "production"
  owner: "datadeling_og_distribusjon"
  system: "geonorge"
