name: dokanalyse-pygeoapi

services: 
  pygeoapi:
    build: .
    ports:
      - "5000:80"
    environment:
      - PYGEOAPI_CONFIG=${PYGEOAPI_CONFIG}
      - PYGEOAPI_API_URL=${PYGEOAPI_API_URL}
      - WSGI_APP=pygeoapi.starlette_app:APP
      - WSGI_WORKER_CLASS=uvicorn.workers.UvicornH11Worker
      - DOKANALYSE_APP_FILES_DIR=/mnt/dokanalyse
      - DOKANALYSE_DATASETS_CONFIG_DIR=/mnt/dokanalyse/config
      - DOKANALYSE_AR5_FGDB_PATH=
      - DOKANALYSE_SOCKET_IO_SRV_URL=${DOKANALYSE_SOCKET_IO_SRV_URL}
      - DOKANALYSE_AZURE_BLOB_STORAGE_CONN_STR=${DOKANALYSE_AZURE_BLOB_STORAGE_CONN_STR}
      - DOKANALYSE_LOCAL_FILE_SHARE_DIR=/mnt/dokanalyse/fileshare
      - DOKANALYSE_LOCAL_FILE_SHARE_BASE_URL=${DOKANALYSE_LOCAL_FILE_SHARE_BASE_URL}
      - DOKANALYSE_PDF_TEMPLATES_DIR=${DOKANALYSE_PDF_TEMPLATES_DIR}
      - DOKANALYSE_DATASETS=${DOKANALYSE_DATASETS}
      - DOKANALYSE_USE_XML_SCHEMAS=${DOKANALYSE_USE_XML_SCHEMAS}
      - DOKANALYSE_CACHE_ON_STARTUP=${DOKANALYSE_CACHE_ON_STARTUP}
      - DOKANALYSE_CLIENT_TIMEOUT=${DOKANALYSE_CLIENT_TIMEOUT}
      - DOKANALYSE_LOG_LEVEL=${DOKANALYSE_LOG_LEVEL}
      - NAP_USERNAME=${NAP_USERNAME}
      - NAP_PASSWORD=${NAP_PASSWORD}
    volumes:
      - ${DOKANALYSE_APP_FILES_DIR}:/mnt/dokanalyse
      - ${DOKANALYSE_DATASETS_CONFIG_DIR}:/mnt/dokanalyse/config
      - ${DOKANALYSE_LOCAL_FILE_SHARE_DIR}:/mnt/dokanalyse/fileshare