server:
  bind:
    host: 0.0.0.0
    port: 5000
  url: http://localhost:5000
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  languages:
    - en-US
  pretty_print: true
  limit: 10
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

logging:
  level: INFO

metadata:
  identification:
    title:
      en: OGC API - DOK-analyse
    description:
      en: OGC API er en ny generasjon standarder fra Open Geospatial Consortium. På denne serveren tilbys implementasjon av arealanalyse av DOK-datasett
    keywords:
      en:
        - OGC
        - Geospatial
        - Geodata
        - Data
        - API
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://www.kartverket.no

  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: Kartverket
    url: https://www.kartverket.no
  contact:
    name: Kartverket
    email: post@kartverket.no
    url: https://www.kartverket.no

resources:
  # dokanalyse:
  #   type: process
  #   processor:
  #     name: dokanalyse.DokanalyseProcessor

  reguleringsplaner:
    type: collection
    title:
      en: Reguleringsplaner
    description:
      en: 'Reguleringsplan er et arealplankart med tilhørende bestemmelser som fastlegger bruk, 
        flerbruk og vern i bestemte områder, og som gir grunnlag for avklaring av hvilke bygge- og anleggstiltak 
        som kan gjennomføres i planområdet.'
    keywords:
      en:
        - Reguleringsplan
        - Arealplan
        - Områdeplan
        - Detaljplan
    extents:
      spatial:
        bbox: [4.499171, 57.979522, 31.168594, 71.134022]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: 172.28.64.1
          dbname: reguleringsplaner
          user: postgres
          password: "061214"
          search_path: [reguleringsplaner_vn2_c267b67cd67f4d149a79fd0bf46a9e61]
        id_field: objid
        table: rpomrade_omrade
        geom_field: omrade
        crs:
          - http://www.opengis.net/def/crs/OGC/1.3/CRS84
          - http://www.opengis.net/def/crs/EPSG/0/25832
          - http://www.opengis.net/def/crs/EPSG/0/25833
          - http://www.opengis.net/def/crs/EPSG/0/25835
          - http://www.opengis.net/def/crs/EPSG/0/4258
          - http://www.opengis.net/def/crs/EPSG/0/4326
          - http://www.opengis.net/def/crs/EPSG/0/3857
        storage_crs: http://www.opengis.net/def/crs/EPSG/0/25833
